# Generated by Django 3.2 on 2021-04-06 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_de_inicio', models.DateField(verbose_name='Data de início')),
                ('data_de_termino', models.DateField(verbose_name='Data de término')),
                ('valor', models.FloatField(verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('projeto_vinculado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos.projeto')),
            ],
        ),
    ]
