# Generated by Django 3.2 on 2021-04-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='risco',
            field=models.IntegerField(choices=[(0, 'Baixo'), (1, 'Médio'), (2, 'Alto')], default=0),
        ),
    ]
