# Generated by Django 3.2 on 2021-04-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_risco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor'),
        ),
    ]
