# Generated by Django 3.2 on 2021-04-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_projeto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='valor',
            field=models.IntegerField(verbose_name='Valor'),
        ),
    ]
